spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jwt_blacklisted
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            use-new-id-generator-mappings: false